config/routes.rb
Rails.application.routes.draw do

  get "/uanet", to: "records#index"
  resources :records, path: '/uanet/records'
  get '/uanet/records', to: redirect('/uanet')
  match '/uanet/records/:id/approve', to: 'records#approve', as: 'records_approve', via: :patch
  get '/uanet/export', to: 'records#export', as: :records_export

  get '/uanet/signup', to: 'users#new', as: 'new_user'
  resources :users, except: [:new], path: '/uanet/users'
  get '/uanet/admin', as: 'admin', to: 'users#admin'

  scope '/uanet' do
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true, length: { minimum: 2, maximum: 30 }, uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  validates :password, length: { minimum: 6, maximum: 20 }, on: :create
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_no_user, only: [:new, :create]
  before_action :require_admin, only: [:destroy, :index]

  def index
    @users = User.all.paginate(page: params[:page], per_page: 20)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if verify_recaptcha(model: @user) && @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Ласкаво просимо!"
        redirect_to user_path(@user)
    else
        render 'new'
    end

  end

  def edit
  end

  def update

    if @user.update(user_params)
      flash[:notice] = "Дані користувача оновлено."
      redirect_to records_path
    else
      render 'edit'
    end

  end

  def show
    user_records = Record.where(user_id: @user.id)
    @approved_records = user_records.where(approved: true).order(created_at: :desc).paginate(page: params[:approved_page], per_page: 10)
    @pending_records = user_records.where(approved: false).order(created_at: :desc).paginate(page: params[:pending_page], per_page: 5)
  end

  def admin
    @pending_records = Record.where(approved: false).paginate(page: params[:page], per_page: 20)
  end

  def destroy
    @user.destroy
    flash[:alert] = "Користувача видалено."
    redirect_to users_path
  end


  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "Ви можете редагувати тільки свій профіль."
      redirect_to user_path(@user)
    end
  end

  def require_no_user
    if logged_in?
      flash[:alert] = "Ви вже маєте один акаунт. Його можна оновити."
      redirect_to records_path
    end
  end

  def require_admin
    if !logged_in? || !current_user.admin?
      flash[:alert] = "Тільки адміни можуть видаляти користувачів."
      redirect_to records_path
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |t| %>
<%= render 'shared/errors', obj: @user %>

   <p>
     <%= t.label :username, 'Псевдо:' %>
     <%= t.text_field :username, placeholder: "Введіть псевдо", autofocus: true %>
   </p>

   <p>
     <%= t.label :email, 'Емейл:' %>
     <%= t.email_field :email, placeholder: "Введіть емейл", autofocus: true %>
   </p>

   <p>
     <%= t.label :password, 'Пароль:' %>
     <%= t.password_field :password, placeholder: "Введіть пароля" %>
   </p>

   <% if !logged_in? %>
    <p><%= recaptcha_tags hl: 'uk' %></p>
   <% end %>

   <p>
     <%= t.submit(@user.new_record? ? "Зареєструватися" : "Оновити дані користувача") %>
   </p>

<% end %>

<p><%= link_to 'До списку записів', records_path %></p>

app/views/users/admin.html.erb
<% @pending_records.each do |record| %>

  <p><%= link_to record.name, record_path(record) %> —
     <%= link_to record.user.username, user_path(record.user) %> —
     <%= link_to 'Схвалити', records_approve_path(record),
          method: :patch,
          data: { confirm: 'Схвалити?' } %> —
     <%= link_to 'Видалити', record_path(record),
          method: :destroy,
          data: { confirm: 'Видалити?' } %>
  </p>

<% end %>

<p><%= will_paginate @pending_records %></p>

<%= link_to 'Назад', records_path %>

app/views/users/edit.html.erb
<h1 class="center">Редагувати користувача <u><%= @user.username %></u></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<table>
  <tr>
    <th>Псевдо</th>
    <th>Емейл</th>
    <th colspan='3'>Опції</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Профіль', user_path(user) %></td>
      <td><%= link_to 'Редагувати', edit_user_path(user) %></td>
      <td><%= link_to 'Видалити', user_path(user),
                  method: :delete,
                  data: { confirm: 'Точно видалити?' } %></td>
    </tr>
  <% end %>

</table>

<p><%= will_paginate %></p>

<p><%= link_to 'До списку записів', records_path %></p>

app/views/users/new.html.erb
<h1 class="center">Зареєструватися</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Сторінка користувача <u><%= @user.username %></u></h1>

<p><%= link_to 'До повного списку записів', records_path %></p>

<% if logged_in? && @user == current_user %>
  <p><%= link_to 'Редагувати профіль', edit_user_path %> — <%= link_to 'Вилогінитись', logout_path, method: :delete %></p>

  <p><b><%= link_to 'Додати новий запис', new_record_path %></b></p>
<% end %>

<h2>Додане користувачем:</h2>

<table>
  <tr>
    <th>Назва</th>
    <th>Рік</th>
    <th>Веб-архів</th>
    <th>Посилання (якщо живий)</th>
    <th>Коментарі</th>
    <th>Коли</th>
    <th colspan="3">Опції</th>
  </tr>

  <% @approved_records.each do |record| %>
    <tr>
      <td><%= record.name %></td>
      <td><%= record.first_year %></td>
      <td><%= link_to truncate(record.webarchive, length: 30), record.webarchive, target: "_blank" %></td>
      <td><%= link_to truncate(record.link, length: 50), record.link, target: "_blank" %></td>
      <td><%= record.comment %></td>
      <td><%= record.created_at.strftime('%Y-%m-%d') %></td>
      <td><%= link_to 'Докладніше', record_path(record) %></td>
      <% if logged_in? && (record.user == current_user || current_user.admin?) %>
        <td><%= link_to 'Редагувати', edit_record_path(record) %></td>
      <% end %>
      <% if logged_in? && current_user.admin? %>
        <td><%= link_to 'Видалити', record_path(record),
                method: :delete,
                data: { confirm: 'Точно видалити?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<p><%= will_paginate @approved_records, param_name: :approved_page %></p>

<% if @pending_records.any? && logged_in? && (@user == current_user || current_user.admin?) %>
  <h2>Записи на розгляді:</h2>

  <table>
    <tr>
      <th>Назва</th>
      <th>Рік</th>
      <th>Веб-архів</th>
      <th>Посилання (якщо живий)</th>
      <th>Коментарі</th>
      <th>Коли</th>
      <th colspan="3">Опції</th>
    </tr>

  <% @pending_records.each do |record| %>
    <tr>
      <td><%= record.name %></td>
      <td><%= record.first_year %></td>
      <td><%= link_to truncate(record.webarchive, length: 30), record.webarchive, target: "_blank" %></td>
      <td><%= link_to truncate(record.link, length: 50), record.link, target: "_blank" %></td>
      <td><%= record.comment %></td>
      <td><%= record.created_at.strftime('%Y-%m-%d') %></td>
      <td><%= link_to 'Докладніше', record_path(record) %></td>
      <td><%= link_to 'Редагувати', edit_record_path(record) %></td>
      <% if logged_in? && current_user.admin? %>
        <td><%= link_to 'Видалити', record_path(record),
                method: :delete,
                data: { confirm: 'Точно видалити?' } %></td>
      <% end %>
    </tr>
  <% end %>
  </table>

  <p><%= will_paginate @pending_records, param_name: :pending_page %></p>
<% end %>