config/routes.rb
Rails.application.routes.draw do

  get "/uanet", to: "records#index"
  resources :records, path: '/uanet/records'
  get '/uanet/records', to: redirect('/uanet')
  match '/uanet/records/:id/approve', to: 'records#approve', as: 'records_approve', via: :patch
  get '/uanet/export', to: 'records#export', as: :records_export

  get '/uanet/signup', to: 'users#new', as: 'new_user'
  resources :users, except: [:new], path: '/uanet/users'
  get '/uanet/admin', as: 'admin', to: 'users#admin'

  scope '/uanet' do
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, uniqueness: true
  validates :first_year, presence: true

  VALID_WEBARCHIVE_REGEX = /\Ahttps:\/\/web.archive.org\/web\/\S{5,}/i
  validates :webarchive, presence: true, uniqueness: true, format: { with: VALID_WEBARCHIVE_REGEX }
  VALID_LINK_REGEX = /\A(?:(?:https?|ftp):\/\/)(?:\S+(?::\S*)?@)?(?:(?!10(?:\.\d{1,3}){3})(?!127(?:\.\d{1,3}){3})(?!169\.254(?:\.\d{1,3}){2})(?!192\.168(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]+-?)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]+-?)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,})))(?::\d{2,5})?(?:\/[^\s]*)?\z/i
  validates :link, format: { with: VALID_LINK_REGEX }, allow_blank: true


  def self.to_csv
    attributes = %w{id name first_year webarchive link comment}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |record|
        csv << attributes.map{ |attr| record.send(attr) }
      end
    end
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  before_action :set_record, only: [:edit, :update, :show, :destroy, :approve]
  before_action :require_user, except: [:index, :show, :export]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy, :approve]
  helper_method :sort_column, :sort_direction

  def index
    @records = Record.where(approved: true).order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 20)
  end

  def show
  end

  def new
    @record = Record.new
  end

  def edit
  end

  def create
    @record = Record.new(record_params)
    @record.user = current_user

    if current_user.admin?
      @record.update_attribute(:approved, approve_param[:approved] => true)
    end

    if @record.save
      redirect_to records_path
    else
      render 'new'
    end
  end

  def update
    if @record.update(record_params)
      redirect_to record_path
    else
      render 'edit'
    end
  end

  def approve
    @record.update_attribute(:approved, approve_param[:approved] => true)

    redirect_to admin_path
  end

  def export
    @records = Record.where(approved: true).order(:created_at)
    respond_to do |format|
      format.html { redirect_to records_path }
      format.csv { send_data @records.to_csv, filename: "records-#{Time.zone.now.to_s(:number)}.csv" }
    end
  end

  def destroy
    @record.destroy

    redirect_to records_path
  end

  private
    def record_params
      params.require(:record).permit(:name, :first_year, :webarchive, :link, :comment, :description, :approved)
    end

    def approve_param
      params.permit(:record)
    end

    def set_record
      @record = Record.find(params[:id])
    end

    def require_same_user
     if current_user != @record.user && !current_user.admin?
        flash[:alert] = "Ви можете редагувати тільки власні записи."
        redirect_to records_path
     end
    end

    def require_admin
      if !current_user.admin?
        flash[:alert] = "Тільки адміни можуть це робити."
        redirect_to records_path
      end
    end

    def sort_column
      Record.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_with model: @record, local: true do |form| %>

<%= render 'shared/errors', obj: @record %>

  <p>
    <%= form.label :name, '*Назва:' %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :first_year, '*Встановлений рік народження сайту:' %><br>
    <%= form.select :first_year, (1990)..(2005)  %>
  </p>

  <p>
    <%= form.label :webarchive, '*Посилання на перший кеш вебархіву:' %><br>
    <%= form.text_area :webarchive %>
  </p>

  <p>
    <%= form.label :link, 'Посилання на сайт (якщо живий):' %><br>
    <%= form.text_area :link %>
  </p>

  <p>
    <%= form.label :comment, 'Коментар:' %><br>
    <%= form.text_area :comment %>
  </p>

  <p>
    <%= form.label :description, 'Опис  (працює markdown):' %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/records/edit.html.erb
<h1>Редагувати запис</h1>

<%= render 'form' %>

<p><%= link_to 'До запису', record_path(@record) %></p>
<p><%= link_to 'До списку записів', records_path %></p>

app/views/records/index.html.erb
<h1>База старих сайтів УАнету (з 1990-их)</h1>

<p>Докладніше — <a href="https://bebyx.co.ua/web-archive.html" target="_blank">Старі сайти УАнету</a></p>

<% if logged_in? %>
  <p><%= link_to "Користувач #{current_user.username}", user_path(current_user) %> — <%= link_to 'Вилогінитись', logout_path, method: :delete %></p>
  <p><b><%= link_to 'Додати новий запис', new_record_path %></b></p>
<% else %>
  <p><%= link_to 'Залогіньтеся', login_path %> чи <%= link_to 'зареєструйтеся', '/uanet/signup' %>, щоб додати новий запис</p>
<% end %>

<h2>Список сайтів</h2>

<p><%= link_to "Вивантажити в CSV", records_export_path(format: "csv") %></p>

<table>
  <tr>
    <th><%= sortable 'name', 'Назва' %></th>
    <th><%= sortable 'first_year', 'Рік' %></th>
    <th>Веб-архів</th>
    <th>Посилання (якщо живий)</th>
    <th>Коментарі</th>
    <th><%= sortable 'user_id', 'Ким' %></th>
    <th><%= sortable 'created_at', 'Коли' %></th>
    <th colspan="3">Опції</th>
  </tr>

  <% @records.each do |record| %>
    <tr>
      <td><%= link_to record.name, record_path(record) %></td>
      <td><%= record.first_year %></td>
      <td><%= link_to truncate(record.webarchive, length: 30), record.webarchive, target: "_blank" %></td>
      <td><%= link_to truncate(record.link, length: 50), record.link, target: "_blank" %></td>
      <td><%= record.comment %></td>
      <td><%= link_to record.user.username, user_path(record.user) %></td>
      <td><%= record.created_at.strftime('%Y-%m-%d') %></td>
      <td><%= link_to 'Докладніше', record_path(record) %></td>

      <% if logged_in? && (record.user == current_user || current_user.admin?) %>
        <td><%= link_to 'Редагувати', edit_record_path(record) %></td>
      <% end %>
      <% if logged_in? && current_user.admin? %>
        <td><%= link_to 'Видалити', record_path(record),
              method: :delete,
              data: { confirm: 'Точно видалити?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<p><%= will_paginate %></p>

<% if logged_in? && current_user.admin? %>
  <p><%= link_to 'Користувачі', users_path %></p>
  <p><%= link_to 'Модерувати нові записи', admin_path %>
<% end %>

app/views/records/new.html.erb
<h1>Новий запис</h1>

<%= render 'form' %>

<p><%= link_to 'До списку записів', records_path %></p>

app/views/records/show.html.erb
<h1><%= @record.name %></h1>

<p><b>Встановлений рік народження: </b><%= @record.first_year %></p>

<p><%= link_to 'Перший кеш вебархіву', @record.webarchive, target: "_blank" %></p>

<p><%= @record.link %></p>

<p><%= @record.comment %></p>

<p><%= markdown(@record.description) %></p>

<% if logged_in? && (@record.user == current_user || current_user.admin?) %>
  <%= link_to "Редагувати", edit_record_path(@record) %>
<% end %>
<% if logged_in? && current_user.admin? %>
  <%= link_to "Видалити", record_path(@record),
                             method: :delete,
                             data: {confirm: "Точно видалити?"} %>
<% end %>


<p><%= link_to 'До списку записів', records_path %></p>